name: Test React App
on: push
jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Get code in repository
            uses: actions/checkout@v3 
        - name: Install node_modules
            run: npm ci
        - name: Test application
            run: npm run test





        

